object CourseCreate: TCourseCreate
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = #1050#1091#1088#1089
  ClientHeight = 459
  ClientWidth = 855
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 24
    Top = 48
    Width = 179
    Height = 112
    BevelOuter = bvNone
    TabOrder = 0
    Visible = False
    object Button2: TButton
      Left = 8
      Top = 61
      Width = 161
      Height = 41
      Caption = #1056#1077#1072#1083#1100#1085#1086#1089#1090#1100
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnClick = Button1Click
    end
    object Button1: TButton
      Left = 8
      Top = 8
      Width = 161
      Height = 41
      Caption = #1055#1083#1072#1085
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = Button1Click
    end
  end
  object Panel2: TPanel
    Left = 232
    Top = 8
    Width = 249
    Height = 209
    BevelOuter = bvNone
    TabOrder = 1
    Visible = False
    object Label1: TLabel
      Left = 16
      Top = 8
      Width = 113
      Height = 25
      Caption = #1055#1088#1086#1075#1088#1072#1084#1084#1072':'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object ListBox1: TListBox
      Left = 0
      Top = 45
      Width = 249
      Height = 164
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ItemHeight = 18
      ParentFont = False
      TabOrder = 0
      OnDblClick = ListBox1DblClick
    end
  end
  object Panel3: TPanel
    Left = 24
    Top = 223
    Width = 249
    Height = 209
    BevelOuter = bvNone
    TabOrder = 2
    Visible = False
    object Label2: TLabel
      Left = 16
      Top = 8
      Width = 88
      Height = 25
      Caption = #1050#1072#1073#1080#1085#1077#1090':'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object ListBox2: TListBox
      Left = 0
      Top = 39
      Width = 249
      Height = 164
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ItemHeight = 18
      ParentFont = False
      TabOrder = 0
      OnDblClick = ListBox2DblClick
    end
  end
  object Panel4: TPanel
    Left = 504
    Top = 9
    Width = 249
    Height = 209
    BevelOuter = bvNone
    TabOrder = 3
    Visible = False
    object Label3: TLabel
      Left = 16
      Top = 8
      Width = 67
      Height = 25
      Caption = #1057#1084#1077#1085#1072':'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object ListBox3: TListBox
      Left = 0
      Top = 48
      Width = 249
      Height = 164
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ItemHeight = 18
      ParentFont = False
      TabOrder = 0
      OnDblClick = ListBox3DblClick
    end
  end
  object Panel5: TPanel
    Left = 392
    Top = 299
    Width = 345
    Height = 57
    BevelOuter = bvNone
    TabOrder = 4
    Visible = False
    object Label4: TLabel
      Left = 16
      Top = 16
      Width = 177
      Height = 25
      Caption = #1050#1086#1083'-'#1074#1086' '#1089#1090#1091#1076#1077#1085#1090#1086#1074':'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Edit1: TEdit
      Left = 200
      Top = 13
      Width = 62
      Height = 33
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object Button3: TButton
      Left = 280
      Top = 13
      Width = 51
      Height = 33
      Caption = 'OK'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = Button3Click
    end
  end
end
